class GratitudeError(Exception):
    # Base class for all errors originating from the gratitude app.

    def __init__(self, message="Internal server error."):
        self.message = message
        self.return_val = {
            'error': {
                'message': self.message
            }
        }
        self.type = None
        self.return_val['error']['type'] = self.type

    def get(self):
        return self.return_val


class ValidationError(GratitudeError):
    # Messages are generated by flask_marshmallow.

    def __init__(self, message):
        GratitudeError.__init__(self, message)
        self.type = 'validation'
        self.return_val['error']['type'] = self.type


class NotFoundError(GratitudeError):
    # Called when trying to access a resource that does not exist.

    def __init__(self, resource_name, resource_id):
        message = "{} with ID {} was not found.".format(
            resource_name.capitalize(), resource_id
        )
        GratitudeError.__init__(self, message)
        self.type = 'not_found'
        self.return_val['error']['type'] = self.type


class BadReqError(GratitudeError):
    # Called if input data is invalid (ex: invalid json)

    def __init__(self, message):
        GratitudeError.__init__(self, message)
        self.type = 'bad_req'
        self.return_val['error']['type'] = self.type
